### ISSUE TITLE
ability to ignore some folders

### ISSUE THREAD

**Issue by ahmet-cetinkaya** [IdreesInc/Waypoint#41] opened 2022-09-17 14:22 UTC
I think there should be a setting option where we can ignore some folders. For example, we don't want to include the attachments folder in waypoints.

**Comment by lucasstern** [comment] 2022-11-14 00:41
Duplicate of https://github.com/IdreesInc/Waypoint/issues/37

**Closed** 2022-11-14 11:23 UTC
